// This file is auto-generated by drizzle-zod
// Do not edit this file directly

import type { InferInsertModel, InferSelectModel } from 'drizzle-orm';
import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import * as schema from './schema';

// User schemas
export const userSchema = createSelectSchema(schema.users);
export const insertUserSchema = createInsertSchema(schema.users);
export type User = InferSelectModel<typeof schema.users>;
export type InsertUser = InferInsertModel<typeof schema.users>;

// Board schemas
export const boardSchema = createSelectSchema(schema.boards);
export const insertBoardSchema = createInsertSchema(schema.boards);
export type Board = InferSelectModel<typeof schema.boards>;
export type InsertBoard = InferInsertModel<typeof schema.boards>;

// Asset schemas
export const assetSchema = createSelectSchema(schema.assets);
export const insertAssetSchema = createInsertSchema(schema.assets);
export type Asset = InferSelectModel<typeof schema.assets>;
export type InsertAsset = InferInsertModel<typeof schema.assets>;

// Search schemas
export const searchSchema = createSelectSchema(schema.searches);
export const insertSearchSchema = createInsertSchema(schema.searches);
export type Search = InferSelectModel<typeof schema.searches>;
export type InsertSearch = InferInsertModel<typeof schema.searches>;

// BoardAsset schemas
export const boardAssetSchema = createSelectSchema(schema.boardAssets);
export const insertBoardAssetSchema = createInsertSchema(schema.boardAssets);
export type BoardAsset = InferSelectModel<typeof schema.boardAssets>;
export type InsertBoardAsset = InferInsertModel<typeof schema.boardAssets>;

// BoardCollaborator schemas
export const boardCollaboratorSchema = createSelectSchema(
  schema.boardCollaborators
);
export const insertBoardCollaboratorSchema = createInsertSchema(
  schema.boardCollaborators
);
export type BoardCollaborator = InferSelectModel<
  typeof schema.boardCollaborators
>;
export type InsertBoardCollaborator = InferInsertModel<
  typeof schema.boardCollaborators
>;

// LikedAsset schemas
export const likedAssetSchema = createSelectSchema(schema.likedAssets);
export const insertLikedAssetSchema = createInsertSchema(schema.likedAssets);
export type LikedAsset = InferSelectModel<typeof schema.likedAssets>;
export type InsertLikedAsset = InferInsertModel<typeof schema.likedAssets>;

// ViewedAsset schemas
export const viewedAssetSchema = createSelectSchema(schema.viewedAssets);
export const insertViewedAssetSchema = createInsertSchema(schema.viewedAssets);
export type ViewedAsset = InferSelectModel<typeof schema.viewedAssets>;
export type InsertViewedAsset = InferInsertModel<typeof schema.viewedAssets>;

// LikedBoard schemas
export const likedBoardSchema = createSelectSchema(schema.likedBoards);
export const insertLikedBoardSchema = createInsertSchema(schema.likedBoards);
export type LikedBoard = InferSelectModel<typeof schema.likedBoards>;
export type InsertLikedBoard = InferInsertModel<typeof schema.likedBoards>;

// ViewedBoard schemas
export const viewedBoardSchema = createSelectSchema(schema.viewedBoards);
export const insertViewedBoardSchema = createInsertSchema(schema.viewedBoards);
export type ViewedBoard = InferSelectModel<typeof schema.viewedBoards>;
export type InsertViewedBoard = InferInsertModel<typeof schema.viewedBoards>;

// RecentAsset schemas
export const recentAssetSchema = createSelectSchema(schema.recentAssets);
export const insertRecentAssetSchema = createInsertSchema(schema.recentAssets);
export type RecentAsset = InferSelectModel<typeof schema.recentAssets>;
export type InsertRecentAsset = InferInsertModel<typeof schema.recentAssets>;

// RecentBoard schemas
export const recentBoardSchema = createSelectSchema(schema.recentBoards);
export const insertRecentBoardSchema = createInsertSchema(schema.recentBoards);
export type RecentBoard = InferSelectModel<typeof schema.recentBoards>;
export type InsertRecentBoard = InferInsertModel<typeof schema.recentBoards>;

// Report schemas
export const reportSchema = createSelectSchema(schema.reports);
export const insertReportSchema = createInsertSchema(schema.reports);
export type Report = InferSelectModel<typeof schema.reports>;
export type InsertReport = InferInsertModel<typeof schema.reports>;
